ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) += cam_flash_dev.o cam_flash_core.o cam_flash_soc.o
