ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_isp/isp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_xiaomi/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += isp_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_isp_dev.o cam_isp_context.o
